today = datestr(now, 'yyyy-mm-dd');

curr_path = pwd;

% Match all ../data/spm_first_levell_results/*_EventsOrig_instrsep_2runs/SPM.mat files
spmfiles = dir(fullfile(curr_path, '..', 'data', 'spm_first_level_results', '*_EventsOrig_instrsep_2runs', 'SPM.mat'));
spmfiles = strcat({spmfiles.folder}', filesep, {spmfiles.name}');
spmfiles = cellstr(spmfiles)';

%% Contrast: Sem_sentminusPerc_sent
ss=struct(...
    'swd',fullfile(curr_path, '..', 'replication_results', 'spm_ss', ['parcels_Sem_sentminusPerc_sent_', today]),...
    'files_spm',{spmfiles},...                            
    'EffectOfInterest_contrasts',{{'Sem_sentminusPerc_sent'}},...    
    'Localizer_contrasts',{{'Sem_sentminusPerc_sent'}},... 
    'Localizer_thr_type', {{'none'}},...
    'Localizer_thr_p',[.05],... 
    'overlap_thr',.10,...	  
    'type','GcSS',...        
    'smooth',6,... 
    'model',1,...                                          
    'ExplicitMasking', [], ...
    'estimation','OLS',...
    'ask','none');                        
ss=spm_ss_design(ss);
ss=spm_ss_estimate(ss);


%% Contrast: Sem_photominusPerc_photo
ss=struct(...
    'swd',fullfile(curr_path, '..', 'replication_results', 'spm_ss', ['parcels_Sem_photominusPerc_photo_', today]),...
    'files_spm',{spmfiles},...                            
    'EffectOfInterest_contrasts',{{'Sem_photominusPerc_photo'}},...    
    'Localizer_contrasts',{{'Sem_photominusPerc_photo',}},...   
    'Localizer_thr_type', {{'none'}},...
    'Localizer_thr_p',[.05],... 
    'overlap_thr',.10,...	  
    'type','GcSS',...        
    'smooth',6,... 
    'model',1,...
    'ExplicitMasking', [], ...
    'estimation','OLS',...
    'ask','none');
ss=spm_ss_design(ss);
ss=spm_ss_estimate(ss);


%% Contrast: Sem_sentminusSem_photo + Sem_sentminusPerc_sent, conjunction using and
ss=struct(...
    'swd',fullfile(curr_path, '..', 'replication_results', 'spm_ss', ['parcels_Sem_sentminusSem_photo_and_Sem_sentminusPerc_sent_', today]),...
    'files_spm',{spmfiles},...                            
    'EffectOfInterest_contrasts',{{'Sem_sentminusPerc_sent', 'Sem_photominusPerc_photo'}},... 
    'Localizer_contrasts',{{'Sem_sentminusPerc_sent', 'Sem_photominusPerc_photo'}},...  
    'Localizer_thr_type', {{'none', 'none'}},...
    'Localizer_thr_p',[.05, .05],... 
    'overlap_thr',.10,...	  
    'type','GcSS',...        
    'smooth',6,... 
    'model',1,...
    'ExplicitMasking', [], ...
    'estimation','OLS',...
    'ask','none');
ss=spm_ss_design(ss);
ss=spm_ss_estimate(ss);

%% Contrast: S-N

today = datestr(now, 'yyyy-mm-dd');

curr_path = pwd;

% Match all ../data/spm_first_levell_results/*_EventsOrig_instrsep_2runs/SPM.mat files
spmfiles = dir(fullfile(curr_path, '..', 'data', 'spm_first_level_results', '*_SWNlocIPS168_3runs', 'SPM.mat'));
spmfiles = strcat({spmfiles.folder}', filesep, {spmfiles.name}');
spmfiles = cellstr(spmfiles)';

ss=struct(...
    'swd',fullfile(curr_path, '..', 'replication_results', 'spm_ss', ['parcels_S-N_', today]),...
    'files_spm',{spmfiles},...                            
    'EffectOfInterest_contrasts',{{'S-N'}},...    
    'Localizer_contrasts',{{'S-N',}},...   
    'Localizer_thr_type', {{'none'}},...
    'Localizer_thr_p',[.001],... 
    'overlap_thr_vox',.10,...	  
    'overlap_thr_roi', .8,...
    'type','GcSS',...        
    'smooth',6,... 
    'model',1,...
    'ExplicitMasking', [], ...
    'estimation','OLS',...
    'ask','none');
ss=spm_ss_design(ss);

%%
ss=spm_ss_estimate(ss);
