today = datestr(now, 'yyyy-mm-dd');

curr_path = pwd;

% EventsOrig spm files
spmfiles = dir(fullfile(curr_path, '..', 'data', 'spm_first_level_results', '*_EventsOrig_instrsep_2runs', 'SPM.mat'));
spmfiles = strcat({spmfiles.folder}', filesep, {spmfiles.name}');
eventsorig_spmfiles = cellstr(spmfiles)';

% SWN spm files
spmfiles = dir(fullfile(curr_path, '..', 'data', 'spm_first_level_results', '*_SWNlocIPS168_3runs', 'SPM.mat'));
spmfiles = strcat({spmfiles.folder}', filesep, {spmfiles.name}');
swn_spmfiles = cellstr(spmfiles)';

% parcels
events_parcels_file = fullfile(curr_path, '..', 'data', 'spm_first_level_results', 'Events.nii');
language_parcels_file = fullfile(curr_path, '..', 'data', 'spm_first_level_results', 'Language.nii');

%% Parcels-based spatial correlation
bcc=struct(...
    'swd',fullfile(curr_path, '..', 'data', 'spm_ss_results', ['spcorr_parcels_Events_EventsOrig2EventsOrig_', today]),...
    'EffectOfInterest1_spm',{eventsorig_spmfiles},...  
    'EffectOfInterest2_spm', {eventsorig_spmfiles},...
    'EffectOfInterest1_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...
    'EffectOfInterest2_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...                           
    'ManualROIs', events_parcels_file,...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', [], ...
    'ask','none');   
bcc=spm_bcc_design(bcc);
bcc=spm_bcc_estimate(bcc);

bcc=struct(...
    'swd',fullfile(curr_path, '..', 'data', 'spm_ss_results', ['spcorr_parcels_Language_EventsOrig2EventsOrig_', today]),...
    'EffectOfInterest1_spm',{eventsorig_spmfiles},...  
    'EffectOfInterest2_spm', {eventsorig_spmfiles},...
    'EffectOfInterest1_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...
    'EffectOfInterest2_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...                           
    'ManualROIs', language_parcels_file,...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', [], ...
    'ask','none');   
bcc=spm_bcc_design(bcc);
bcc=spm_bcc_estimate(bcc);


bcc=struct(...
    'swd',fullfile(curr_path, '..', 'data', 'spm_ss_results', ['spcorr_parcels_Events_EventsOrig2SWN_', today]),...
    'EffectOfInterest1_spm',{eventsorig_spmfiles},...  
    'EffectOfInterest2_spm', {swn_spmfiles},...
    'EffectOfInterest1_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...
    'EffectOfInterest2_contrasts',{{'S' 'W' 'N'}},...                           
    'ManualROIs', events_parcels_file,...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', [], ...
    'ask','none');   
bcc=spm_bcc_design(bcc);
bcc=spm_bcc_estimate(bcc);

bcc=struct(...
    'swd',fullfile(curr_path, '..', 'data', 'spm_ss_results', ['spcorr_parcels_Language_EventsOrig2SWN_', today]),...
    'EffectOfInterest1_spm',{eventsorig_spmfiles},...  
    'EffectOfInterest2_spm', {swn_spmfiles},...
    'EffectOfInterest1_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...
    'EffectOfInterest2_contrasts',{{'S' 'W' 'N'}},...                           
    'ManualROIs', language_parcels_file,...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', [], ...
    'ask','none');   
bcc=spm_bcc_design(bcc);
bcc=spm_bcc_estimate(bcc);


bcc=struct(...
    'swd',fullfile(curr_path, '..', 'data', 'spm_ss_results', ['spcorr_parcels_Events_SWN2EventsOrig_', today]),...
    'EffectOfInterest2_spm',{eventsorig_spmfiles},...  
    'EffectOfInterest1_spm', {swn_spmfiles},...
    'EffectOfInterest2_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...
    'EffectOfInterest1_contrasts',{{'S' 'W' 'N'}},...                           
    'ManualROIs', events_parcels_file,...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', [], ...
    'ask','none');   
bcc=spm_bcc_design(bcc);
bcc=spm_bcc_estimate(bcc);

bcc=struct(...
    'swd',fullfile(curr_path, '..', 'data', 'spm_ss_results', ['spcorr_parcels_Language_SWN2EventsOrig_', today]),...
    'EffectOfInterest2_spm',{eventsorig_spmfiles},...  
    'EffectOfInterest1_spm', {swn_spmfiles},...
    'EffectOfInterest2_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...
    'EffectOfInterest1_contrasts',{{'S' 'W' 'N'}},...                           
    'ManualROIs', language_parcels_file,...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', [], ...
    'ask','none');   
bcc=spm_bcc_design(bcc);
bcc=spm_bcc_estimate(bcc);


bcc=struct(...
    'swd',fullfile(curr_path, '..', 'data', 'spm_ss_results', ['spcorr_parcels_Events_SWN2SWN_', today]),...
    'EffectOfInterest1_spm',{swn_spmfiles},...  
    'EffectOfInterest2_spm', {swn_spmfiles},...
    'EffectOfInterest1_contrasts',{{'S' 'W' 'N'}},...
    'EffectOfInterest2_contrasts',{{'S' 'W' 'N'}},...                           
    'ManualROIs', events_parcels_file,...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', [], ...
    'ask','none');   
bcc=spm_bcc_design(bcc);
bcc=spm_bcc_estimate(bcc);

bcc=struct(...
    'swd',fullfile(curr_path, '..', 'data', 'spm_ss_results', ['spcorr_parcels_Language_SWN2SWN_', today]),...
    'EffectOfInterest1_spm',{swn_spmfiles},...  
    'EffectOfInterest2_spm', {swn_spmfiles},...
    'EffectOfInterest1_contrasts',{{'S' 'W' 'N'}},...
    'EffectOfInterest2_contrasts',{{'S' 'W' 'N'}},...                           
    'ManualROIs', language_parcels_file,...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', [], ...
    'ask','none');   
bcc=spm_bcc_design(bcc);
bcc=spm_bcc_estimate(bcc);

%% ROI

roi_label = 'S-N';

% Sem-Perc_Both
% roi_files = dir(fullfile(curr_path, '..', 'data', 'spm_first_level_results', '*_EventsOrig_instrsep_2runs', 'locT_conjunction_0009_percene2fbeb545e8538fc631a5b658897462d_d51fd8e6a075650259d79e425ef95cc5.ROIs.nii'));

% Sem-Perc_Sent
% roi_files = dir(fullfile(curr_path, '..', 'data', 'spm_first_level_results', '*_EventsOrig_instrsep_2runs', 'locT_0009_percentile-ROI-leva24e3979931e708a651794ceb617213f_d51fd8e6a075650259d79e425ef95cc5.ROIs.nii'));

% Sem-Perc_Photo
% roi_files = dir(fullfile(curr_path, '..', 'data', 'spm_first_level_results', '*_EventsOrig_instrsep_2runs', 'locT_0011_percentile-ROI-levb81abf9a5eb2f9763055c84b4ce0fa50_d51fd8e6a075650259d79e425ef95cc5.ROIs.nii'));

% S-N
roi_files = dir(fullfile(curr_path, '..', 'data', 'spm_first_level_results', '*_SWNlocIPS168_3runs', 'locT_0004_percentile-ROI-lev108e4c18d6ea2abe6e93878e9ec37706_0ec4c2aea138a29651934fa82423479c.ROIs.nii'));

roi_files = strcat({roi_files.folder}', filesep, {roi_files.name}');
roi_files = cellstr(roi_files)';

bcc=struct(...
    'swd',fullfile(curr_path, '..', 'data', 'spm_ss_results', ['spcorr_frois_', roi_label, '_EventsOrig2EventsOrig_', today]),...
    'EffectOfInterest1_spm',{eventsorig_spmfiles},...  
    'EffectOfInterest2_spm', {eventsorig_spmfiles},...
    'EffectOfInterest1_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...
    'EffectOfInterest2_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...                           
    'ManualROIs', {roi_files},...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', [], ...
    'ask','none');   
bcc=spm_bcc_design(bcc);
bcc=spm_bcc_estimate(bcc);

bcc=struct(...
    'swd',fullfile(curr_path, '..', 'data', 'spm_ss_results', ['spcorr_frois_', roi_label, '_EventsOrig2SWN_', today]),...
    'EffectOfInterest1_spm',{eventsorig_spmfiles},...  
    'EffectOfInterest2_spm', {swn_spmfiles},...
    'EffectOfInterest1_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...
    'EffectOfInterest2_contrasts',{{'S' 'W' 'N'}},...                           
    'ManualROIs', {roi_files},...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', [], ...
    'ask','none');   
bcc=spm_bcc_design(bcc);
bcc=spm_bcc_estimate(bcc);

bcc=struct(...
    'swd',fullfile(curr_path, '..', 'data', 'spm_ss_results', ['spcorr_frois_', roi_label, '_SWN2EventsOrig_', today]),...
    'EffectOfInterest2_spm',{eventsorig_spmfiles},...  
    'EffectOfInterest1_spm', {swn_spmfiles},...
    'EffectOfInterest2_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...
    'EffectOfInterest1_contrasts',{{'S' 'W' 'N'}},...                           
    'ManualROIs', {roi_files},...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', [], ...
    'ask','none');   
bcc=spm_bcc_design(bcc);
bcc=spm_bcc_estimate(bcc);


bcc=struct(...
    'swd',fullfile(curr_path, '..', 'data', 'spm_ss_results', ['spcorr_frois_', roi_label, '_SWN2SWN_', today]),...
    'EffectOfInterest1_spm',{swn_spmfiles},...  
    'EffectOfInterest2_spm', {swn_spmfiles},...
    'EffectOfInterest1_contrasts',{{'S' 'W' 'N'}},...
    'EffectOfInterest2_contrasts',{{'S' 'W' 'N'}},...                           
    'ManualROIs', {roi_files},...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', [], ...
    'ask','none');   
bcc=spm_bcc_design(bcc);
bcc=spm_bcc_estimate(bcc);


