%% Use Events Localizers
today = datestr(now, 'yyyy-mm-dd');

curr_path = pwd;

% Match all ../data/spm_first_level_results/*_EventsOrig_instrsep_2runs/SPM.mat files
spmfiles = dir(fullfile(curr_path, '..', 'data', 'spm_first_level_results', '*_EventsOrig_instrsep_2runs', 'SPM.mat'));
spmfiles = strcat({spmfiles.folder}', filesep, {spmfiles.name}');
eventsorig_spmfiles = cellstr(spmfiles)';

% Match all ../data/spm_first_level_results/*_SWNlocIPS168_3runs/SPM.mat files
spmfiles = dir(fullfile(curr_path, '..', 'data', 'spm_first_level_results', '*_SWNlocIPS168_3runs', 'SPM.mat'));
spmfiles = strcat({spmfiles.folder}', filesep, {spmfiles.name}');
swn_spmfiles = cellstr(spmfiles)';

%% Parcel file
parcel_file = fullfile(curr_path, '..', 'data', 'spm_first_level_results', 'Events.nii');


%% EventsOrig (both) -> EventsOrig effects
ss=struct(...
    'swd',fullfile(curr_path, '..', 'replication_results', 'spm_ss', ['Effect_EventsBoth2EventsOrig_', today]),...
    'EffectOfInterest_spm',{eventsorig_spmfiles},...  
    'Localizer_spm', {eventsorig_spmfiles},...
    'EffectOfInterest_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...
    'Localizer_contrasts',{{'Sem_sentminusPerc_sent', 'Sem_photominusPerc_photo'}},...    
    'Localizer_thr_type',{{'percentile-ROI-level'}},...
    'Localizer_thr_p',[.1],... 
    'Localizer_conjunction_type', 'max',...
    'type','mROI',...                       
    'ManualROIs', parcel_file,...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', '', ...
    'estimation','OLS',...
    'ask','none');   
ss=spm_ss_design(ss);
ss=spm_ss_estimate(ss);

%% EventsOrig (photo) -> EventsOrig effects
ss=struct(...
    'swd',fullfile(curr_path, '..', 'replication_results', 'spm_ss', ['Effect_EventsPhoto2EventsOrig_', today]),...
    'EffectOfInterest_spm',{eventsorig_spmfiles},...  
    'Localizer_spm', {eventsorig_spmfiles},...
    'EffectOfInterest_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...
    'Localizer_contrasts',{{'Sem_photominusPerc_photo'}},...    
    'Localizer_thr_type',{{'percentile-ROI-level'}},...
    'Localizer_thr_p',[.1],... 
    'type','mROI',...                       
    'ManualROIs', parcel_file,...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', '', ...
    'estimation','OLS',...
    'ask','none');   
ss=spm_ss_design(ss);
ss=spm_ss_estimate(ss);

%% EventsOrig (sent) -> EventsOrig effects
ss=struct(...
    'swd',fullfile(curr_path, '..', 'replication_results', 'spm_ss', ['Effect_EventsSent2EventsOrig_', today]),...
    'EffectOfInterest_spm',{eventsorig_spmfiles},...  
    'Localizer_spm', {eventsorig_spmfiles},...
    'EffectOfInterest_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...
    'Localizer_contrasts',{{'Sem_sentminusPerc_sent'}},...    
    'Localizer_thr_type',{{'percentile-ROI-level'}},...
    'Localizer_thr_p',[.1],... 
    'type','mROI',...                       
    'ManualROIs', parcel_file,...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', '', ...
    'estimation','OLS',...
    'ask','none');   
ss=spm_ss_design(ss);
ss=spm_ss_estimate(ss);


%% EventsOrig (both) -> SWN effects
ss=struct(...
    'swd',fullfile(curr_path, '..', 'replication_results', 'spm_ss', ['Effect_EventsBoth2SWN_', today]),...
    'EffectOfInterest_spm',{swn_spmfiles},...  
    'Localizer_spm', {eventsorig_spmfiles},...
    'EffectOfInterest_contrasts',{{'S', 'W', 'N'}},...
    'Localizer_contrasts',{{'Sem_sentminusPerc_sent', 'Sem_photominusPerc_photo'}},...    
    'Localizer_thr_type',{{'percentile-ROI-level'}},...
    'Localizer_thr_p',[.1],... 
    'Localizer_conjunction_type', 'max',...
    'type','mROI',...                       
    'ManualROIs', parcel_file,...
    'overwrite', 1, ...
    'model',1,...
    'ExplicitMasking', '', ...
    'estimation','OLS',...
    'ask','none');
ss=spm_ss_design(ss);
ss=spm_ss_estimate(ss);

%% EventsOrig (photo) -> SWN effects
ss=struct(...
    'swd',fullfile(curr_path, '..', 'replication_results', 'spm_ss', ['Effect_EventsPhoto2SWN_', today]),...
    'EffectOfInterest_spm',{swn_spmfiles},...  
    'Localizer_spm', {eventsorig_spmfiles},...
    'EffectOfInterest_contrasts',{{'S', 'W', 'N'}},...
    'Localizer_contrasts',{{'Sem_photominusPerc_photo'}},...    
    'Localizer_thr_type',{{'percentile-ROI-level'}},...
    'Localizer_thr_p',[.1],... 
    'type','mROI',...                       
    'ManualROIs', parcel_file,...
    'overwrite', 1, ...
    'model',1,...
    'ExplicitMasking', '', ...
    'estimation','OLS',...
    'ask','none');
ss=spm_ss_design(ss);
ss=spm_ss_estimate(ss);

%% EventsOrig (sent) -> SWN effects
ss=struct(...
    'swd',fullfile(curr_path, '..', 'replication_results', 'spm_ss', ['Effect_EventsSent2SWN_', today]),...
    'EffectOfInterest_spm',{swn_spmfiles},...  
    'Localizer_spm', {eventsorig_spmfiles},...
    'EffectOfInterest_contrasts',{{'S', 'W', 'N'}},...
    'Localizer_contrasts',{{'Sem_sentminusPerc_sent'}},...    
    'Localizer_thr_type',{{'percentile-ROI-level'}},...
    'Localizer_thr_p',[.1],... 
    'type','mROI',...                       
    'ManualROIs', parcel_file,...
    'overwrite', 1, ...
    'model',1,...
    'ExplicitMasking', '', ...
    'estimation','OLS',...
    'ask','none');
ss=spm_ss_design(ss);
ss=spm_ss_estimate(ss);

%% Use Language localizers
% Parcel file
parcel_file = fullfile(curr_path, '..', 'data', 'spm_first_level_results', 'Language.nii');

%% SWN -> EventsOrig effects
ss=struct(...
    'swd',fullfile(curr_path, '..', 'replication_results', 'spm_ss', ['Effect_SWN2EventsOrig_', today]),...
    'EffectOfInterest_spm',{eventsorig_spmfiles},...  
    'Localizer_spm', {swn_spmfiles},...
    'EffectOfInterest_contrasts',{{'Sem_photo' 'Perc_photo' 'Sem_sent' 'Perc_sent'}},...
    'Localizer_contrasts',{{'S-N'}},...    
    'Localizer_thr_type',{{'percentile-ROI-level'}},...
    'Localizer_thr_p',[.1],... 
    'type','mROI',...                       
    'ManualROIs', parcel_file,...
    'overwrite', 1, ...
    'model',1,...                                   
    'ExplicitMasking', '', ...
    'estimation','OLS',...
    'ask','none');   
ss=spm_ss_design(ss);
ss=spm_ss_estimate(ss);

%% SWN -> SWN effects
ss=struct(...
    'swd',fullfile(curr_path, '..', 'replication_results', 'spm_ss', ['Effect_SWN2SWN_', today]),...
    'EffectOfInterest_spm',{swn_spmfiles},...  
    'Localizer_spm', {swn_spmfiles},...
    'EffectOfInterest_contrasts',{{'S', 'W', 'N'}},...
    'Localizer_contrasts',{{'S-N'}},...    
    'Localizer_thr_type',{{'percentile-ROI-level'}},...
    'Localizer_thr_p',[.1],... 
    'type','mROI',...                       
    'ManualROIs', parcel_file,...
    'overwrite', 1, ...
    'model',1,...
    'ExplicitMasking', '', ...
    'estimation','OLS',...
    'ask','none');
ss=spm_ss_design(ss);
ss=spm_ss_estimate(ss);
